# Generated by Django 4.2.7 on 2025-07-15 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_add_bookmark_model'),
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user became interested in this hobby')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='forums.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Hobby',
                'verbose_name_plural': 'User Hobbies',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['-joined_at'], name='accounts_us_joined__39c733_idx'), models.Index(fields=['user', '-joined_at'], name='accounts_us_user_id_a4a9ad_idx')],
                'unique_together': {('user', 'subcategory')},
            },
        ),
    ]
