# Generated by Django 4.2.7 on 2025-07-15 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_userhobby_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('image', models.ImageField(help_text='Upload a photo (max 10MB). Supported formats: JPG, JPEG, PNG, GIF, WebP.', upload_to='photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for your photo.', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_ph_user_id_a9e3d6_idx')],
            },
        ),
    ]
