# Generated by Django 4.2.7 on 2025-07-15 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_photo_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Status of the friend request', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the friend request was accepted or rejected', null=True)),
                ('from_user', models.ForeignKey(help_text='User who sent the friend request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(help_text='User who received the friend request', on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_user', 'status'], name='accounts_fr_from_us_8a2689_idx'), models.Index(fields=['to_user', 'status'], name='accounts_fr_to_user_c999b2_idx'), models.Index(fields=['-created_at'], name='accounts_fr_created_0bb620_idx')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
