# Generated by Django 4.2.7 on 2025-07-15 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_friendship_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='When the last message was sent in this conversation', null=True)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined this conversation')),
                ('last_read_at', models.DateTimeField(blank=True, help_text='When the user last read messages in this conversation', null=True)),
                ('conversation', models.ForeignKey(help_text='The conversation this participant is part of', on_delete=django.db.models.deletion.CASCADE, to='accounts.conversation')),
                ('user', models.ForeignKey(help_text='The user participating in the conversation', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(help_text='Users participating in this conversation', related_name='conversations', through='accounts.ConversationParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('content', models.TextField(help_text='The message content')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the message was sent')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read')),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='message_set', to='accounts.conversation')),
                ('sender', models.ForeignKey(blank=True, help_text='User who sent this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['conversation', '-sent_at'], name='accounts_me_convers_414791_idx'), models.Index(fields=['sender', '-sent_at'], name='accounts_me_sender__8fce4c_idx'), models.Index(fields=['-sent_at'], name='accounts_me_sent_at_52ecfb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', '-joined_at'], name='accounts_co_user_id_235ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation', 'user'], name='accounts_co_convers_f0c59b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='accounts_co_last_me_2714b7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-created_at'], name='accounts_co_created_991543_idx'),
        ),
    ]
