# Generated by Django 4.2.7 on 2025-11-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_conversation_conversationparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_forum_admin',
            field=models.BooleanField(default=False, help_text='Forum administrator with full administrative privileges'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_forum_moderator',
            field=models.BooleanField(default=False, help_text='Forum moderator with content moderation privileges'),
        ),
    ]
