# Generated by Django 4.2.7 on 2025-11-03 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_forum_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='from_user',
            field=models.ForeignKey(help_text='User who sent the hubby request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_hubby_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When the hubby request was accepted or rejected', null=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Status of the hubby request', max_length=10),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='to_user',
            field=models.ForeignKey(help_text='User who received the hubby request', on_delete=django.db.models.deletion.CASCADE, related_name='received_hubby_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
