# Generated by Django 4.2.7 on 2025-07-15 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned threads appear at the top')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked threads cannot receive new posts')),
                ('view_count', models.IntegerField(default=0, help_text='Number of times this thread has been viewed')),
                ('post_count', models.IntegerField(default=0, help_text='Number of posts in this thread')),
                ('last_post_at', models.DateTimeField(help_text='Timestamp of the most recent post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forums.subcategory')),
            ],
            options={
                'ordering': ['-is_pinned', '-last_post_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('content', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forums.thread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['-is_pinned', '-last_post_at'], name='forums_thre_is_pinn_e5ba2b_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['subcategory', 'slug'], name='forums_thre_subcate_9cfc4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together={('subcategory', 'slug')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['thread', 'created_at'], name='forums_post_thread__b17401_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='forums_post_author__30c918_idx'),
        ),
    ]
