# Generated by Django 4.2.7 on 2025-07-15 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0002_thread_post_thread_forums_thre_is_pinn_e5ba2b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote_count',
            field=models.IntegerField(default=0, help_text='Number of upvotes for this post'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forums.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', '-created_at'], name='forums_vote_post_id_efd773_idx'), models.Index(fields=['user', '-created_at'], name='forums_vote_user_id_9aba87_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
