# Generated by Django 4.2.7 on 2025-07-15 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0003_add_vote_model_and_vote_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='forums.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='forums_book_created_84fb54_idx'), models.Index(fields=['user', '-created_at'], name='forums_book_user_id_27087b_idx')],
                'unique_together': {('user', 'thread')},
            },
        ),
    ]
