# Generated by Django 4.2.7 on 2025-07-15 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0004_add_bookmark_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('query', models.CharField(help_text='The search query text', max_length=200)),
                ('content_type', models.CharField(choices=[('all', 'All Content'), ('posts', 'Posts'), ('threads', 'Threads'), ('users', 'Users'), ('categories', 'Categories')], default='all', help_text='Type of content searched', max_length=20)),
                ('results_count', models.PositiveIntegerField(default=0, help_text='Number of results returned for this search')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='forums_sear_user_id_250107_idx'), models.Index(fields=['query', '-created_at'], name='forums_sear_query_98a9ad_idx'), models.Index(fields=['-created_at'], name='forums_sear_created_c4330a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('name', models.CharField(help_text='User-defined name for this saved search', max_length=100)),
                ('query', models.CharField(help_text='The search query text', max_length=200)),
                ('content_type', models.CharField(choices=[('all', 'All Content'), ('posts', 'Posts'), ('threads', 'Threads'), ('users', 'Users'), ('categories', 'Categories')], default='all', help_text='Type of content to search', max_length=20)),
                ('sort_by', models.CharField(choices=[('relevance', 'Relevance'), ('date_desc', 'Newest First'), ('date_asc', 'Oldest First'), ('author', 'Author A-Z')], default='relevance', help_text='Default sort order for this search', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this saved search is active')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this saved search was last used', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='forums_save_user_id_9334b9_idx'), models.Index(fields=['user', 'is_active', '-updated_at'], name='forums_save_user_id_29761c_idx'), models.Index(fields=['-last_used_at'], name='forums_save_last_us_a4bd6c_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
