# Generated by Django 4.2.7 on 2025-07-16 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0005_add_search_history_and_saved_searches'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when object was last updated')),
                ('session_key', models.CharField(help_text='Session key for anonymous users or session-based tracking', max_length=40)),
                ('query', models.CharField(help_text='The search query text', max_length=200)),
                ('normalized_query', models.CharField(help_text='Normalized query for analytics (lowercase, stemmed)', max_length=200)),
                ('content_type', models.CharField(choices=[('all', 'All Content'), ('posts', 'Posts'), ('threads', 'Threads'), ('users', 'Users'), ('categories', 'Categories')], default='all', help_text='Type of content searched', max_length=20)),
                ('sort_by', models.CharField(choices=[('relevance', 'Relevance'), ('date_desc', 'Newest First'), ('date_asc', 'Oldest First'), ('author', 'Author A-Z')], default='relevance', help_text='Sort order used', max_length=20)),
                ('results_count', models.PositiveIntegerField(default=0, help_text='Number of results returned')),
                ('search_time_ms', models.PositiveIntegerField(default=0, help_text='Time taken to execute search in milliseconds')),
                ('database_hits', models.PositiveIntegerField(default=1, help_text='Number of database queries executed')),
                ('clicked_result_position', models.PositiveIntegerField(blank=True, help_text='Position of clicked result (1-based), null if no click', null=True)),
                ('clicked_result_type', models.CharField(blank=True, help_text='Type of content that was clicked', max_length=20, null=True)),
                ('time_to_click_ms', models.PositiveIntegerField(blank=True, help_text='Time from search to click in milliseconds', null=True)),
                ('page_number', models.PositiveIntegerField(default=1, help_text='Page number viewed (for pagination analysis)')),
                ('user_agent', models.CharField(blank=True, help_text='User agent string for device/browser analytics', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for geographic analytics (anonymized)', null=True)),
                ('referrer_url', models.URLField(blank=True, help_text='Referring URL that led to search')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user if authenticated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Analytics',
                'verbose_name_plural': 'Search Analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', '-created_at'], name='forums_sear_query_4437e9_idx'), models.Index(fields=['normalized_query', '-created_at'], name='forums_sear_normali_3ab14e_idx'), models.Index(fields=['user', '-created_at'], name='forums_sear_user_id_ab97ed_idx'), models.Index(fields=['session_key', '-created_at'], name='forums_sear_session_06a3c3_idx'), models.Index(fields=['content_type', '-created_at'], name='forums_sear_content_d99a6b_idx'), models.Index(fields=['-created_at'], name='forums_sear_created_777083_idx'), models.Index(fields=['results_count', '-created_at'], name='forums_sear_results_23789f_idx')],
            },
        ),
    ]
