# Generated by Django 4.2.7 on 2025-08-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_searchanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color_theme',
            field=models.CharField(choices=[('creative-arts', 'Creative & Arts'), ('sports-fitness', 'Sports & Fitness'), ('games-entertainment', 'Games & Entertainment'), ('technology-science', 'Technology & Science'), ('food-culinary', 'Food & Culinary'), ('lifestyle-social', 'Lifestyle & Social')], max_length=20),
        ),
    ]
