# Generated by Django - manual migration
# Migration for adding PostImage model

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_populate_initial_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(
                    help_text='Upload an image (max 10MB). Supported formats: JPG, JPEG, PNG, GIF, WebP.',
                    upload_to='post_images/%Y/%m/',
                    validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]
                )),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order for multiple images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forums.post')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['post', 'order'], name='forums_post_post_id_1a2b3c_idx'),
        ),
    ]
